[package]
name = "xfce4-niri-service"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
authors = ["Antonio Salsi"]
description = "Utility to better integrate Xfce4 applications with the WM niri"
license = "LGPL-2.1-or-later"
repository = "https://github.com/passy1977/xfce4-niri"
homepage = "https://github.com/passy1977/xfce4-niri"
documentation = "https://docs.rs/xfce4-niri"
readme = "../README.md"
keywords = ["niri", "xfce4", "embedded", "posix"]

exclude = [
    "target/",
    ".git/",
    ".github/",
    "*.swp",
    "*.swo",
]

[features]
disable_autostart = []
disable_niri_check = []

[dependencies]
xfce4-niri-lib = { version = "0", path = "../xfce4-niri-lib" }
osal-rs = { git = "https://github.com/HiHappyGarden/osal-rs.git", features = ["posix", "serde"]}
osal-rs-serde = { git = "https://github.com/HiHappyGarden/osal-rs.git", features = ["derive"]}
dbus = "0.9.12"